### ISSUE TITLE
Internal error on bytes data inside pytest params

### ISSUE THREAD

**Issue by tiho44** [Ypurek/pytest-analyzer#3]
We use some encrypted data as pytest.param which causes `INTERNALERROR> TypeError: Object of type bytes is not JSON serializable`

looks like it's handling all data types quite well, and just needs some decoding.

thank you

**Comment by Ypurek** [comment]
could you please provide a little bit more context? Mb steps, commands?
I'll have a look on this issue on the weekend

**Comment by tiho44** [comment]
here's simple example:
```
@pytest.mark.parametrize('param', [b"Hello"])
def test_bytes_param(param):
    assert "Hello" == param.decode("utf-8")

```

thanks a lot!

**Comment by Ypurek** [comment]
issue fixed

**Comment by tiho44** [comment]
thanks a lot for quick fix, work nice
