### ISSUE TITLE
Artifact upload support for dynamically generated tests (pytest)

### ISSUE THREAD

**Issue by AnnLyma** [Ypurek/pytest-analyzer#6]
Pytest dynamic test creation is a popular approach in testing. Is it possible to add artifact uploading support for such tests?

Thanks!

**Comment by poliarush** [comment]
i think it's related to `pytest_generate_tests`

https://pytest-with-eric.com/introduction/pytest-generate-tests/#Example-2-Pytest-Generate-Tests

**Comment by Ypurek** [comment]
will see what I can do

**Comment by AnnLyma** [comment]
closed, with https://github.com/Ypurek/pytest-analyzer/pull/8/commits/3c7bbde984a6d7874db16600cf37b40ca37b60f5 should work fine
